#!/bin/bash


#Web Browser Spam Script


open /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app
open -n /Applications/safari.app